package com.mx.ApiRestCinepolis.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/*---ApiRestCinepolis
CREATE TABLE PELICULAS(
ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, ---YA TENEMOS LOS AUTOINCREMENTABLES
CLAVE VARCHAR2(50) NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
GENERO VARCHAR2(70) NOT NULL,
PRECIO FLOAT NOT NULL
);
*/

@Entity
@Table(name = "PELICULAS")
@NoArgsConstructor
@AllArgsConstructor
@Data
public class Peliculas {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) //Este estereotipo se agrega cuando tenemos el id autoincrementable
	
	@Column(name = "ID", columnDefinition = "Number", nullable = false)
	private Long idPelicula;
	
	@Column(name = "CLAVE", columnDefinition = "VARCHAR2(50)", nullable = false)
	private String clavePelicula;
	
	@Column(name = "NOMBRE", columnDefinition = "VARCHAR2(100)", nullable = false)
	private String nombrePelicula;
	
	@Column(name = "GENERO", columnDefinition = "VARCHAR2(70)", nullable = false)
	private String generoPelicula;
	
	@Column(name = "PRECIO", columnDefinition = "FLOAT", nullable = false)
	private Float precio;

	
	
}
