package com.mx.ApiRestCinepolis.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.NoArgsConstructor;

/*---ApiRestCinepolis
CREATE TABLE PELICULAS(
ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, ---YA TENEMOS LOS AUTOINCREMENTABLES
CLAVE VARCHAR2(50) NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
GENERO VARCHAR2(70) NOT NULL,
PRECIO FLOAT NOT NULL
);
*/

@Entity
@Table(name = "PELICULAS")
@NoArgsConstructor //Constructor vacio
public class Peliculas {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) //Este estereotipo se agrega cuando tenemos el id autoincrementable
	
	@Column(name = "ID", columnDefinition = "Number", nullable = false)
	private Long idPelicula;
	
	@Column(name = "CLAVE", columnDefinition = "VARCHAR2(50)", nullable = false)
	private String clavePelicula;
	
	@Column(name = "NOMBRE", columnDefinition = "VARCHAR2(100)", nullable = false)
	private String nombrePelicula;
	
	@Column(name = "GENERO", columnDefinition = "VARCHAR2(70)", nullable = false)
	private String generoPelicula;
	
	@Column(name = "PRECIO", columnDefinition = "FLOAT", nullable = false)
	private Float precio;

	public Peliculas(Long idPelicula, String clavePelicula, String nombrePelicula, String generoPelicula,
			Float precio) {
		super();
		this.idPelicula = idPelicula;
		this.clavePelicula = clavePelicula;
		this.nombrePelicula = nombrePelicula;
		this.generoPelicula = generoPelicula;
		this.precio = precio;
	}

	@Override
	public String toString() {
		return "Peliculas [idPelicula=" + idPelicula + ", clavePelicula=" + clavePelicula + ", nombrePelicula="
				+ nombrePelicula + ", generoPelicula=" + generoPelicula + ", precio=" + precio + "]";
	}

	public Long getIdPelicula() {
		return idPelicula;
	}

	public void setIdPelicula(Long idPelicula) {
		this.idPelicula = idPelicula;
	}

	public String getClavePelicula() {
		return clavePelicula;
	}

	public void setClavePelicula(String clavePelicula) {
		this.clavePelicula = clavePelicula;
	}

	public String getNombrePelicula() {
		return nombrePelicula;
	}

	public void setNombrePelicula(String nombrePelicula) {
		this.nombrePelicula = nombrePelicula;
	}

	public String getGeneroPelicula() {
		return generoPelicula;
	}

	public void setGeneroPelicula(String generoPelicula) {
		this.generoPelicula = generoPelicula;
	}

	public Float getPrecio() {
		return precio;
	}

	public void setNombre(Float precio) {
		this.precio = precio;
	}
	
	
}
